### ISSUE TITLE
Code action to create a new note doesn't take the right selection range

### ISSUE THREAD

**Issue by mickael-menu** [zk-org/zk#131]
The range used when creating a new note from the visual selection with a code action is incorrect if the buffer is unsaved.

**Comment by tjex** [comment]
@mickael-menu 

Perhaps this got fixed? (Or it's old enough to close?)

Steps I executed:

1. Open a note from zk vault in zk-nvim
2. execute `:e test.md` to create a new buffer (unsaved)
3. Write some text
4. Highlight the text (visual mode)
5. Execute `:ZkNewFromTitleSelection` and also `:ZkNewFromContentSelection`

In both cases of step 5 the note was created successfully.

**Comment by jurica** [comment]
I just reproduces your tests @tjex, seems really to be fixed already.

**Comment by tjex** [comment]
great :) Will close for now then, unless Mickael chimes in to contest
