### ISSUE TITLE
LSP Link doesn't support non-Markdown

### ISSUE THREAD

**Issue by NickHu** [zk-org/zk#362]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [ ] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

I'm trying to use zk with the [Forester](https://www.jonmsterling.com/jms-007N.xml) fileformat, which is a bit like Markdown.
Notably, the link format is the same. 
But the LSP implementation is quite hardcoded to Markdown, namely here:
https://github.com/mickael-menu/zk/blob/be1249d7a60a3096fe4152587e8deefe52a9a45d/internal/adapter/lsp/document.go#L35

### How to reproduce?

Using `zk-nvim`, run the `:ZkInsertLink" command in a new note directory where using the file extension `.tree`

Populating the list of notes does work, but unless I edit the line above, when I trigger the insert I get an error like:
```
Error executing vim.schedule lua callback: RPC[Error] code_name = InvalidRequest, message = "Cannot insert link in 'file:///home/nick/forest/trees/index.tree'" 
```

### zk configuration

```toml
[note]
extension = "tree"
```

### Environment

```bash
zk 0.14.0-5-gbe1249d
system: Linux 6.1.63 x86_64 GNU/Linux
```

**Comment by Dioprz** [comment]
@NickHu Hi, sorry to bother, but I ended up in the same point as you while trying to use Zk with [Typst](https://typst.app/docs), also in neovim. 

Could you give me a hint about what is the required change in that line? I'm not familiar with Go, so I'm struggling understanding what to do.

@mcDevnagh I also want to ask you if this can be a PR you are open to merge? Zk looks like such a promising software to me, but Typst is milles ahead of Latex markdown so I could really appreciate if this could be integrated.

**Comment by mcDevnagh** [comment]
I am unfamiliar with Typst, but adding its language identifier to the [linked line](https://github.com/zk-org/zk/blob/be1249d7a60a3096fe4152587e8deefe52a9a45d/internal/adapter/lsp/document.go#L35) might fix your issue:
```go
if langID != "markdown" && langID != "vimwiki" && langID != "pandoc" && langID != "REPLACE ME" {
```
It's probably `typst`, but I do not know for sure
