### ISSUE TITLE
v0.14.1 homebrew release action failed

### ISSUE THREAD

**Issue by tjex** [zk-org/zk#419]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [ ] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

Lodging this for now, to look at tomorrow. It's late in the evening 🌙

Action: https://github.com/zk-org/zk/actions/runs/9242929309/job/25426386503

### How to reproduce?

na

### zk configuration

```toml
na
```

**Comment by mickael-menu** [comment]
I fixed the issue by [creating a new token](https://github.com/settings/tokens) and modifying the repository secret `HOMEBREW_GITHUB_TOKEN` in Settings > Secrets and variables > Actions.

However the 0.14.1 [was pushed manually on Homebrew by a contributor](https://github.com/Homebrew/homebrew-core/pull/172886) so the GitHub action still failed. That's fine as it's published. 👌

**Comment by tjex** [comment]
@mickael-menu Awesome. Was also looking into this and getting a bit confused about where that token needed to be set.
However, I don't see any token or variable in the orgs settings.

Or is it that we should each generate a token for this github action?

The link takes me to my personal settings/tokens, rather than those for the orgs, which also confused the hell out of me from GitHub documentation.

https://github.com/settings/tokens vs https://github.com/organizations/zk-org/settings/secrets/actions

<img width="989" alt="Screenshot 2024-05-27 at 18 13 40" src="https://github.com/zk-org/zk/assets/83029642/56800a92-c372-4c7b-9715-a45adbe3f9e3">

**Comment by mickael-menu** [comment]
The secrets are per project, so it's in the Settings of the zk repo itself. But I guess it could work in the org secrets as well. 
I'm not sure we can provide a token from the organization itself, I used my personal account to generate the token. I didn't give any access to my personal info or private repo to the token, so that should be fine.

**Comment by tjex** [comment]
oh man. derp. of course 😅

Thanks :)
