### ISSUE TITLE
Use GitHub Actions for building the project

### ISSUE THREAD

**Issue by jurica** [zk-org/zk#421]
See the discussion here: https://github.com/zk-org/zk/discussions/405#discussioncomment-9638348

It would be nice to use GitHub Actions for building and releasing zk.
### Goals
- [x] build linux binaries on actions
- [x] build macOS binaries on actions
- [x] build Windows binaries on actions

**Comment by jurica** [comment]
Just a short update: I didn't forget about this, but apart from some research and local tests haven't done anything more yet. I think that during summer I unfortunately will not find a lot of spare time to spend for doing serious work here. But definitively want to tackle it once the evenings start getting longer and the weather starts getting worse. ;)

**Comment by tjex** [comment]
Not a prob. Thanks for the update.

**Comment by jurica** [comment]
Wohoo, I build the [container images](https://github.com/jurica/zk-xcompile/actions/runs/11975829207) for building (linux) zk binaries and a [set of binaries](https://github.com/jurica/zk/actions/runs/11981324242) on actions.
I'll still need some time to clean up everything and sort out a few minor issues but at least I finally made some progress...

**Comment by jurica** [comment]
I filed two PRs (here and on the xcompile repo) that provides workflows for building the Docker build containers as well as binaries for linux, macOS and Windows.

Looking forward for feedback!
