### ISSUE TITLE
Links not detected when using timestamps as IDs with `link-format = "markdown"`

### ISSUE THREAD

**Issue by WhyNotHugo** [zk-org/zk#426]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [X] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

I'm using timestamps as IDs. I don't think that links to them are being recognised.

### How to reproduce?

I created a dedicated directory with some notes, and added a link from one to another:

```console
> zk graph --format=json | jq

Found 3 notes
{
  "notes": [
    {
      "filename": "202407071252_a-test-note-3.md",
      "filenameStem": "202407071252_a-test-note-3",
      "path": "202407071252_a-test-note-3.md",
      "absPath": "/home/hugo/zk/202407071252_a-test-note-3.md",
      "title": "202407071252 a test note 3",
      "link": "[202407071252 a test note 3](202407071252_a-test-note-3)",
      "lead": "",
      "body": "",
      "snippets": [],
      "rawContent": "# 202407071252 a test note 3\n\n\n",
      "wordCount": 6,
      "tags": [],
      "metadata": {},
      "created": "2024-07-07T10:52:19.632000621Z",
      "modified": "2024-07-07T10:55:40.365477914Z",
      "checksum": "81d551f515932e09cd33f4b66be294874b4d6e64fa8f130acbf0f1d6a006296e"
    },
    {
      "filename": "202407071250_a-test-note.md",
      "filenameStem": "202407071250_a-test-note",
      "path": "202407071250_a-test-note.md",
      "absPath": "/home/hugo/zk/202407071250_a-test-note.md",
      "title": "a test note",
      "link": "[a test note](202407071250_a-test-note)",
      "lead": "",
      "body": "",
      "snippets": [],
      "rawContent": "# a test note\n\n\n",
      "wordCount": 4,
      "tags": [],
      "metadata": {},
      "created": "2024-07-07T10:50:29.013795923Z",
      "modified": "2024-07-07T10:50:30.978769851Z",
      "checksum": "28fb5c59fae677438a21abb7610898a4434292a66a05bfc704e4e9c43bc25218"
    },
    {
      "filename": "202407071246_testing-this.md",
      "filenameStem": "202407071246_testing-this",
      "path": "202407071246_testing-this.md",
      "absPath": "/home/hugo/zk/202407071246_testing-this.md",
      "title": "testing this",
      "link": "[testing this](202407071246_testing-this)",
      "lead": "this is a test note with just a link: [202407071250]",
      "body": "this is a test note with just a link: [202407071250]",
      "snippets": [
        "this is a test note with just a link: [202407071250]"
      ],
      "rawContent": "# testing this\n\nthis is a test note with just a link: [202407071250]\n\n",
      "wordCount": 13,
      "tags": [],
      "metadata": {},
      "created": "2024-07-07T10:46:43.939118945Z",
      "modified": "2024-07-07T10:50:45.802804785Z",
      "checksum": "9061c629b0965b544e4161cf146e7d6ad0036003b9e262c227b867ba7366e10c"
    }
  ],
  "links": []
}
```

Note that the last one has a markdown link to `202407071250`. However, `link` is empty, and both `zk list --link-to 202407071250` and `zk list --link-to 202407071250_a-test-note.md` find zero notes.

### zk configuration

```toml
[note]
template = "default.md"
filename = "{{format-date now 'timestamp'}}_{{slug title}}"

[format.markdown]
link-format = "markdown"
```

My template is:

```
# {{format-date now 'timestamp'}} {{title}}

{{content}}
```

### Environment

```console
> zk --version && echo "system: `uname -srmo`"
zk 
system: Linux 6.9.7-0-edge x86_64 Linux
```

I've installed `zk` from Alpine's repositories. The package version is zk-0.14.1-r2.

**Comment by WhyNotHugo** [comment]
The output of `zk graph` indicates that the link is `202407071250_a-test-note`. Does this mean that I can't just use `202407071250` when using timestamp-based IDs?

**Comment by WhyNotHugo** [comment]
Linking to the basename or full name won't work either, I've tried:

```
this is a test note with just a link: [202407071250]
another link: [202407071250_a-test-note]
another link: [202407071250_a-test-note.md]
```

**Comment by WhyNotHugo** [comment]
I tried setting `id-length = 12`, but that doesn't seem to be the cause.

**Comment by WhyNotHugo** [comment]
Trying to figure out where this parsing happens, but internal/core/note_parse.go:ParseNoteWithContent never seems to get called, nor is internal/adapter/markdown/markdown.go:parseLinks.

**Comment by WhyNotHugo** [comment]
When `internal/adapter/markdown/markdown.go:parseLinks` walks the ast, it only shows these elements:

```
*ast.Document
*ast.Heading
*ast.Text
*ast.Text
*ast.Paragraph
*ast.Text
*ast.Text
*ast.Text
```

Looks like the parser itself is failing to find the link. The parser is goldmark, which is used by several other projects which I use frequently an they all detect links properly. So I don't think that the parser itself is the issue.

**Comment by WhyNotHugo** [comment]
Maybe goldmark doesn't support plain links. E.g.:

    [/path/to/target]

Only aliased links, e.g.:

    [link to target]

    [link to target]: /path/to/target

Or this style:

    [link to target][1]

    [1]: /path/to/target

Or the inline style:

    [link to target](/path/to/target)

To be honest, only the first style makes sense to me in notes that I'll edit manually -- but it seems that goldmark doesn't support these at all.

**Comment by WhyNotHugo** [comment]
I guess this is why `wiki` style is implemented; it's the closest to "bare" markdown links (which would be ideal).

I don't think there's anything actionable that can be done in this scope.

**Comment by tjex** [comment]
@WhyNotHugo 

In your json output, the links do not have their `.md` extensions. This is a specific setting in .zk config:

```toml
# MARKDOWN SETTINGS
[format.markdown]

link-format = "markdown"
link-drop-extension = true
```
This allows for `[link](path/without/extension)` format.

> Linking to the basename or full name won't work either, I've tried:
> 
> ```
> this is a test note with just a link: [202407071250]
> another link: [202407071250_a-test-note]
> another link: [202407071250_a-test-note.md]
> ```

These are also not valid wikilink links. `[incorrect]` -> `[[correct]]`
