### ISSUE TITLE
LSP support for reference links

### ISSUE THREAD

**Issue by tbung** [zk-org/zk#468]
Currently, there is no hover or go to definition action for reference links in the form of
```markdown
This is some text, see [ref] for more info.

[ref]: https://example.com
```

I write a lot of notes on research papers and link the pdf files at the appropriate places, so especially go to definition would be great. I'd be happy to take a stab at it and submit a pull request if you agree this would be a good addition.

**Comment by tjex** [comment]
So just to check I'm understanding correctly, in the above example, go to definition would jump the cursor the the buttom line `[ref]: ...` and hover would bring up a pop-up with the link?

**Comment by tbung** [comment]
Yes, except maybe hover also shows link title (as it is called in the markdown spec) if it exists, so
```markdown
[ref]: https://example.com "Doe, Jane et al., Example Website, 2019"
```
would show both parts of the right side.

Alright, cool, I'll go and try to work something out!
