### ISSUE TITLE
LSP can't resolve documents with custom link-format

### ISSUE THREAD

**Issue by ahmedelgabri** [zk-org/zk#481]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [ ] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

I have the same exact problem right now as #264 . My `link-format` is taken from the docs https://zk-org.github.io/zk/notes/note-format.html#customizing-the-markdown-links-generated-by-zk 

```toml
link-format = "[[{{metadata.id}}|{{title}}]]"
```

But the LSP fails to resolve the link. The document does have an `id` inside its frontmatter and the autocompletion works fine, but the LSP can't find the doc.

### How to reproduce?

[test.zip](https://github.com/user-attachments/files/18147116/test.zip)

Check the link in `b.md`, LSP can't resolve `a.md` using the custom `link-format` inside `.zk/config.toml`

### zk configuration

```toml
[format.markdown]
link-format = "[[{{metadata.id}}|{{title}}]]"
```

### Environment

```bash
zk 0.14.1
system: Darwin 24.2.0 arm64 Darwin
```

**Comment by ahmedelgabri** [comment]
> Hello, @ahmedelgabri. I thing the issue is with your link-format. LSP works pretty fine with the following custom format:
> 
> 
> 
> ```
> 
> link-format = "[[{{filename}}|{{title}}]]"
> 
> ```
> 
> 

Thanks @sivaplaysmC, that was also my guess but what confused me, is that I took it from the docs website and I assumed because it was there that it will work. Maybe the docs need to be updated and avoid adding examples that doesn't work to avoid confusion.

**Comment by tjex** [comment]
Markdown links resolve to the actual filenames. This is why `{{filename}}` is working for you.

This `link-format = "[[{{metadata.id}}|{{title}}]]"` still works, but only if your config is setup to use `metadata.id` as the filename.

I've implemented this in the notebook you shared.
[test-tjex.zip](https://github.com/user-attachments/files/18219346/test-tjex.zip)
